Questão 16
RCabral91/react-components-exercises-1 pull request #8
Opened 2022-03-22 13:39 UTC by RCabral91

16. Crie um componente que recebe dois números e retorna o valor
                da soma entre eles.

2022-03-22 18:45 UTC, fredsvanelli requested changes

2022-03-22 18:45 UTC, fredsvanelli commented on src/components/Q16Sum/index.tsx
> +};
Da pra retornar direto em 1 linha

2022-03-22 20:57 UTC, RCabral91 commented on src/components/Q16Sum/index.tsx
> +};
nao consegui

2022-03-24 02:55 UTC, fredsvanelli submitted a review, later dismissed

2022-03-28 11:59 UTC, fredsvanelli approved these changes

2022-03-29 15:07 UTC, fredsvanelli approved these changes

2022-03-29 17:28 UTC, merged